name: ServerBlueMap
version: ${project.version}
main: net.serverplugins.bluemap.ServerBlueMap
api-version: "1.21"
description: BlueMap integration for ServerClaim
author: ServerPlugins
website: https://example.com
depend: [ServerAPI, ServerClaim, BlueMap]

commands:
  poi:
    description: Manage points of interest on the BlueMap
    usage: /poi <add|remove|list|info|hide|show|reload> [args]
    aliases: [pointofinterest, pois]
    permission: serverbluemap.admin

permissions:
  serverbluemap.admin:
    description: Admin permissions for bluemap integration
    default: op
