-- AFK Zones table
CREATE TABLE IF NOT EXISTS server_afk_zones (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(64) NOT NULL UNIQUE,
    world VARCHAR(64) NOT NULL,
    min_x INT NOT NULL,
    min_y INT NOT NULL,
    min_z INT NOT NULL,
    max_x INT NOT NULL,
    max_y INT NOT NULL,
    max_z INT NOT NULL,
    time_interval_seconds INT DEFAULT 300,
    enabled BOOLEAN DEFAULT TRUE,
    use_rank_multipliers BOOLEAN DEFAULT TRUE,
    holo_world VARCHAR(64) DEFAULT NULL,
    holo_x DOUBLE DEFAULT NULL,
    holo_y DOUBLE DEFAULT NULL,
    holo_z DOUBLE DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Zone Rewards table (supports CURRENCY, ITEM, COMMAND, XP types)
CREATE TABLE IF NOT EXISTS server_afk_rewards (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    zone_id INT NOT NULL,
    reward_type VARCHAR(16) NOT NULL,
    currency_amount DOUBLE DEFAULT 0,
    item_data TEXT DEFAULT NULL,
    command_data TEXT DEFAULT NULL,
    xp_amount INT DEFAULT 0,
    chance_percent DOUBLE DEFAULT 100.0,
    FOREIGN KEY (zone_id) REFERENCES server_afk_zones(id) ON DELETE CASCADE
);

-- Player Statistics table
CREATE TABLE IF NOT EXISTS server_afk_player_stats (
    player_uuid VARCHAR(36) PRIMARY KEY,
    total_afk_time_seconds BIGINT DEFAULT 0,
    total_rewards_received INT DEFAULT 0,
    total_currency_earned DOUBLE DEFAULT 0,
    total_xp_earned INT DEFAULT 0,
    sessions_completed INT DEFAULT 0,
    first_afk_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_afk_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    favorite_zone_id INT DEFAULT NULL,
    longest_session_seconds BIGINT DEFAULT 0,
    current_streak_days INT DEFAULT 0,
    best_streak_days INT DEFAULT 0,
    last_daily_reward_date DATE DEFAULT NULL,
    FOREIGN KEY (favorite_zone_id) REFERENCES server_afk_zones(id) ON DELETE SET NULL
);

-- AFK Session History table
CREATE TABLE IF NOT EXISTS server_afk_session_history (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_uuid VARCHAR(36) NOT NULL,
    zone_id INT NOT NULL,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP DEFAULT NULL,
    duration_seconds BIGINT DEFAULT 0,
    rewards_earned INT DEFAULT 0,
    currency_earned DOUBLE DEFAULT 0,
    xp_earned INT DEFAULT 0,
    was_verified BOOLEAN DEFAULT FALSE,
    ended_by_combat BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (zone_id) REFERENCES server_afk_zones(id) ON DELETE CASCADE
);

-- Activity Tracking table (for anti-exploit pattern analysis)
CREATE TABLE IF NOT EXISTS server_afk_activity_log (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_uuid VARCHAR(36) NOT NULL,
    activity_type VARCHAR(32) NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    location_x INT NOT NULL,
    location_y INT NOT NULL,
    location_z INT NOT NULL,
    world VARCHAR(64) NOT NULL,
    metadata TEXT DEFAULT NULL
);

-- Pattern Analysis Results table
CREATE TABLE IF NOT EXISTS server_afk_pattern_analysis (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_uuid VARCHAR(36) NOT NULL,
    analysis_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    pattern_type VARCHAR(32) NOT NULL,
    confidence_score DOUBLE NOT NULL,
    flagged_for_review BOOLEAN DEFAULT FALSE,
    auto_action_taken VARCHAR(32) DEFAULT NULL,
    admin_reviewed BOOLEAN DEFAULT FALSE,
    admin_notes TEXT DEFAULT NULL
);

-- Verification Challenges table
CREATE TABLE IF NOT EXISTS server_afk_verifications (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_uuid VARCHAR(36) NOT NULL,
    challenge_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    challenge_type VARCHAR(32) NOT NULL,
    response_time TIMESTAMP DEFAULT NULL,
    passed BOOLEAN DEFAULT FALSE,
    response_time_seconds INT DEFAULT NULL
);

-- Add gems_amount column to rewards (for existing installations)
ALTER TABLE server_afk_rewards ADD COLUMN IF NOT EXISTS gems_amount INT DEFAULT 0;

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_afk_rewards_zone ON server_afk_rewards(zone_id);
CREATE INDEX IF NOT EXISTS idx_session_history_player ON server_afk_session_history(player_uuid);
CREATE INDEX IF NOT EXISTS idx_session_history_zone ON server_afk_session_history(zone_id);
CREATE INDEX IF NOT EXISTS idx_session_history_start ON server_afk_session_history(start_time);
CREATE INDEX IF NOT EXISTS idx_activity_log_player ON server_afk_activity_log(player_uuid);
CREATE INDEX IF NOT EXISTS idx_activity_log_time ON server_afk_activity_log(timestamp);
CREATE INDEX IF NOT EXISTS idx_pattern_analysis_player ON server_afk_pattern_analysis(player_uuid);
CREATE INDEX IF NOT EXISTS idx_pattern_analysis_flagged ON server_afk_pattern_analysis(flagged_for_review);
CREATE INDEX IF NOT EXISTS idx_verifications_player ON server_afk_verifications(player_uuid);
