package net.serverplugins.velocity.resourcepack;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.Reader;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Map;
import java.util.Properties;
import org.slf4j.Logger;

/**
 * Configuration manager for ServerResourcePack Velocity plugin.
 *
 * <p>Handles loading and accessing protocol-to-resource-pack mappings from config.properties.
 * Optionally loads a pack-manifest.json generated by server-items to override URLs and hashes.
 */
public class ResourcePackConfig {

    private final Path dataDirectory;
    private final Logger logger;
    private final Properties properties;
    private boolean manifestLoaded;

    // Configuration keys
    private static final String KEY_PACK_REQUIRED = "pack.required";
    private static final String KEY_PACK_PROMPT = "pack.prompt";
    private static final String KEY_PACK_SEND_DELAY_TICKS = "pack.send-delay-ticks";
    private static final String KEY_PACK_BASE_URL = "pack.base-url";

    // Default values
    private static final boolean DEFAULT_PACK_REQUIRED = true;
    private static final String DEFAULT_PACK_PROMPT =
            "ServerPlugins Resource Pack\\nRequired for custom items and UI";
    private static final int DEFAULT_PACK_SEND_DELAY_TICKS = 0;
    private static final String DEFAULT_PACK_BASE_URL = "http://localhost:8080/packs/";

    public ResourcePackConfig(Path dataDirectory, Logger logger) {
        this.dataDirectory = dataDirectory;
        this.logger = logger;
        this.properties = new Properties();
    }

    /**
     * Loads the configuration from disk, creating default config if it doesn't exist.
     *
     * @throws IOException if config cannot be loaded or created
     */
    public void load() throws IOException {
        if (!Files.exists(dataDirectory)) {
            Files.createDirectories(dataDirectory);
        }

        Path configPath = dataDirectory.resolve("config.properties");

        if (!Files.exists(configPath)) {
            createDefaultConfig(configPath);
        }

        try (InputStream in = Files.newInputStream(configPath)) {
            properties.load(in);
        }

        logger.info("Configuration loaded successfully");
    }

    /**
     * Attempts to load a pack-manifest.json from the data directory. If found, overrides
     * protocol-specific URL and hash properties using the base URL from config. Falls back
     * gracefully to existing config.properties values if no manifest is found.
     */
    public void loadManifest() {
        Path manifestPath = dataDirectory.resolve("pack-manifest.json");
        if (!Files.exists(manifestPath)) {
            logger.info("No pack-manifest.json found, using config.properties mappings");
            manifestLoaded = false;
            return;
        }

        try (Reader reader = Files.newBufferedReader(manifestPath)) {
            JsonObject root = JsonParser.parseReader(reader).getAsJsonObject();

            String baseUrl = getBaseUrl();
            if (!baseUrl.endsWith("/")) {
                baseUrl += "/";
            }

            int overrideCount = 0;

            // Override per-protocol mappings
            if (root.has("packs")) {
                JsonObject packs = root.getAsJsonObject("packs");
                for (Map.Entry<String, JsonElement> entry : packs.entrySet()) {
                    String protocol = entry.getKey();
                    JsonObject packEntry = entry.getValue().getAsJsonObject();
                    String file = packEntry.get("file").getAsString();
                    String hash = packEntry.get("hash").getAsString();

                    properties.setProperty("pack." + protocol + ".url", baseUrl + file);
                    properties.setProperty("pack." + protocol + ".hash", hash);
                    overrideCount++;
                }
            }

            // Override default fallback
            if (root.has("default")) {
                JsonObject defaultPack = root.getAsJsonObject("default");
                String file = defaultPack.get("file").getAsString();
                String hash = defaultPack.get("hash").getAsString();

                properties.setProperty("pack.default.url", baseUrl + file);
                properties.setProperty("pack.default.hash", hash);
            }

            String generated =
                    root.has("generated") ? root.get("generated").getAsString() : "unknown";
            manifestLoaded = true;
            logger.info(
                    "Loaded pack manifest ({} protocol mappings, generated: {})",
                    overrideCount,
                    generated);

        } catch (Exception e) {
            logger.warn(
                    "Failed to load pack-manifest.json, falling back to config.properties: {}",
                    e.getMessage());
            manifestLoaded = false;
        }
    }

    /** Returns whether a manifest was successfully loaded. */
    public boolean isManifestLoaded() {
        return manifestLoaded;
    }

    /** Creates a default configuration file with all protocol mappings. */
    private void createDefaultConfig(Path configPath) throws IOException {
        Properties defaults = new Properties();

        // Protocol 774 = Minecraft 1.21.11
        defaults.setProperty("pack.774.url", "http://localhost:8080/packs/serverplugins-1.21.11.zip");
        defaults.setProperty("pack.774.hash", "e19e15a3dca3c9da20d5b4986aa86a187b4c94e8");

        // Protocol 773 = Minecraft 1.21.9-1.21.10
        defaults.setProperty("pack.773.url", "http://localhost:8080/packs/serverplugins-1.21.9.zip");
        defaults.setProperty("pack.773.hash", "3792eb33dfd0565d8a0e674bbd31aae5160dcf55");

        // Protocol 772 = Minecraft 1.21.7-1.21.8
        defaults.setProperty("pack.772.url", "http://localhost:8080/packs/serverplugins-1.21.7.zip");
        defaults.setProperty("pack.772.hash", "8cc8e1434c251dc9e30a14714c3e92cdd56d2cb4");

        // Protocol 771 = Minecraft 1.21.6
        defaults.setProperty("pack.771.url", "http://localhost:8080/packs/serverplugins-1.21.6.zip");
        defaults.setProperty("pack.771.hash", "30da1841b44eecd9dc3f1e157fc7d9bd3f2006a7");

        // Protocol 770 = Minecraft 1.21.5
        defaults.setProperty("pack.770.url", "http://localhost:8080/packs/serverplugins-1.21.4.zip");
        defaults.setProperty("pack.770.hash", "b617f866f8a12b28ff2e9de0a3217a5d27ab1809");

        // Protocol 769 = Minecraft 1.21.4
        defaults.setProperty("pack.769.url", "http://localhost:8080/packs/serverplugins-1.21.4.zip");
        defaults.setProperty("pack.769.hash", "b617f866f8a12b28ff2e9de0a3217a5d27ab1809");

        // Protocol 768 = Minecraft 1.21.3
        defaults.setProperty("pack.768.url", "http://localhost:8080/packs/serverplugins-1.21.3.zip");
        defaults.setProperty("pack.768.hash", "4f8de34dd9d7ba0cbd39314e3506c53a11d1ecfb");

        // Fallback for unknown protocols
        defaults.setProperty(
                "pack.default.url", "http://localhost:8080/packs/serverplugins-1.21.11.zip");
        defaults.setProperty("pack.default.hash", "e19e15a3dca3c9da20d5b4986aa86a187b4c94e8");

        // Pack settings
        defaults.setProperty(KEY_PACK_REQUIRED, String.valueOf(DEFAULT_PACK_REQUIRED));
        defaults.setProperty(KEY_PACK_PROMPT, DEFAULT_PACK_PROMPT);
        defaults.setProperty(
                KEY_PACK_SEND_DELAY_TICKS, String.valueOf(DEFAULT_PACK_SEND_DELAY_TICKS));
        defaults.setProperty(KEY_PACK_BASE_URL, DEFAULT_PACK_BASE_URL);

        try (OutputStream out = Files.newOutputStream(configPath)) {
            defaults.store(
                    out,
                    """
                    ServerResourcePack Velocity Configuration

                    Protocol-to-Resource-Pack Mappings:
                    - pack.<protocol>.url: Direct download URL for the resource pack
                    - pack.<protocol>.hash: SHA-1 hash of the resource pack (40 hex characters)

                    Supported Protocols:
                    - 774: Minecraft 1.21.11
                    - 773: Minecraft 1.21.9-1.21.10
                    - 772: Minecraft 1.21.7-1.21.8
                    - 771: Minecraft 1.21.6
                    - 770: Minecraft 1.21.5
                    - 769: Minecraft 1.21.4
                    - 768: Minecraft 1.21.3
                    - default: Fallback for unknown versions

                    Pack Settings:
                    - pack.required: Whether the resource pack is mandatory (true/false)
                    - pack.prompt: Message shown to players (use \\n for line breaks)
                    - pack.send-delay-ticks: Delay before sending pack offer in ticks (20 ticks = 1 second)
                    - pack.base-url: Base URL for pack downloads (used with pack-manifest.json)

                    Manifest Support:
                    Place a pack-manifest.json (generated by server-items) in this plugin's
                    data directory to automatically override protocol mappings.

                    Note: To generate SHA-1 hash from your pack:
                    sha1sum your-pack.zip | cut -d' ' -f1
                    """);
        }

        logger.info("Created default configuration file with 7 protocol mappings");
    }

    // ========== BASE URL CONFIGURATION ==========

    /**
     * Gets the base URL for constructing pack download URLs from manifest filenames.
     *
     * @return Base URL (e.g., "http://localhost:8080/packs/")
     */
    public String getBaseUrl() {
        return properties.getProperty(KEY_PACK_BASE_URL, DEFAULT_PACK_BASE_URL);
    }

    // ========== PACK URL CONFIGURATION ==========

    /**
     * Gets the resource pack URL for a specific protocol version.
     *
     * @param protocol Minecraft protocol version number
     * @return Resource pack URL, or default URL if protocol not found
     */
    public String getPackUrl(int protocol) {
        String url = properties.getProperty("pack." + protocol + ".url");
        if (url == null || url.isEmpty()) {
            url = getDefaultPackUrl();
            logger.debug("No URL configured for protocol {}, using default", protocol);
        }
        return url;
    }

    /**
     * Gets the default fallback resource pack URL.
     *
     * @return Default resource pack URL
     */
    public String getDefaultPackUrl() {
        return properties.getProperty(
                "pack.default.url", "http://localhost:8080/packs/serverplugins-1.21.11.zip");
    }

    // ========== PACK HASH CONFIGURATION ==========

    /**
     * Gets the resource pack SHA-1 hash for a specific protocol version.
     *
     * @param protocol Minecraft protocol version number
     * @return SHA-1 hash as hex string (40 characters), or default hash if protocol not found
     */
    public String getPackHash(int protocol) {
        String hash = properties.getProperty("pack." + protocol + ".hash");
        if (hash == null || hash.isEmpty()) {
            hash = getDefaultPackHash();
            logger.debug("No hash configured for protocol {}, using default", protocol);
        }
        return hash;
    }

    /**
     * Gets the default fallback resource pack hash.
     *
     * @return Default SHA-1 hash as hex string
     */
    public String getDefaultPackHash() {
        return properties.getProperty(
                "pack.default.hash", "e19e15a3dca3c9da20d5b4986aa86a187b4c94e8");
    }

    /**
     * Checks if a pack configuration exists for the given protocol.
     *
     * @param protocol Minecraft protocol version number
     * @return true if both URL and hash are configured for this protocol
     */
    public boolean hasPackForProtocol(int protocol) {
        String url = properties.getProperty("pack." + protocol + ".url");
        String hash = properties.getProperty("pack." + protocol + ".hash");
        return url != null && !url.isEmpty() && hash != null && !hash.isEmpty();
    }

    // ========== PACK SETTINGS ==========

    /**
     * Gets whether the resource pack is required (kicks player if declined).
     *
     * @return true if pack is required
     */
    public boolean isPackRequired() {
        return Boolean.parseBoolean(
                properties.getProperty(KEY_PACK_REQUIRED, String.valueOf(DEFAULT_PACK_REQUIRED)));
    }

    /**
     * Gets the prompt message shown to players when offering the pack.
     *
     * @return Prompt message (may contain \\n for newlines)
     */
    public String getPackPrompt() {
        return properties.getProperty(KEY_PACK_PROMPT, DEFAULT_PACK_PROMPT);
    }

    /**
     * Gets the delay in ticks before sending the resource pack offer. This prevents race conditions
     * with server connections.
     *
     * @return Delay in ticks (20 ticks = 1 second)
     */
    public int getPackSendDelayTicks() {
        try {
            return Integer.parseInt(
                    properties.getProperty(
                            KEY_PACK_SEND_DELAY_TICKS,
                            String.valueOf(DEFAULT_PACK_SEND_DELAY_TICKS)));
        } catch (NumberFormatException e) {
            logger.warn(
                    "Invalid pack send delay in config, using default: {}",
                    DEFAULT_PACK_SEND_DELAY_TICKS);
            return DEFAULT_PACK_SEND_DELAY_TICKS;
        }
    }
}
